
    """Seed default templates and init MongoDB on startup"""
    init_db()
# Import MongoDB layer (replaces PostgreSQL)
from .db import get_db, init_db, get_mongo_client, MongoCursor

# MongoDB - already configured in src/db.py
                    cur = conn.cursor()
        cur = conn.cursor()
        except pymongo.errors.PyMongoError as e:
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
                cur = conn.cursor()
                cur = conn.cursor()
            cur = conn.cursor()
                    cur = conn.cursor()
                    cur = conn.cursor()
                    cur = conn.cursor()
                    cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
            cur = conn.cursor()
            cur = conn.cursor()
            cur = conn.cursor()
        cur = conn.cursor()
            cur = conn.cursor()
            cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
                cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()
            cur = conn.cursor()
                cur = conn.cursor()
        cur = conn.cursor()
        cur = conn.cursor()